//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST_APIS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocietyClubPortalEntities : DbContext
    {
        public SocietyClubPortalEntities()
            : base("name=SocietyClubPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AVAILABILITY_OF_VENUE> AVAILABILITY_OF_VENUE { get; set; }
        public virtual DbSet<EVENT> EVENT { get; set; }
        public virtual DbSet<POST> POST { get; set; }
        public virtual DbSet<SCHEDULE> SCHEDULE { get; set; }
        public virtual DbSet<SOCIETY> SOCIETY { get; set; }
        public virtual DbSet<SOCIETY_REGISTRATION> SOCIETY_REGISTRATION { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<VENUE> VENUE { get; set; }
    }
}
