//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST_APIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public string NAME { get; set; }
        public string STUDENT_ID { get; set; }
        public string SOCIETY_NAME { get; set; }
    
        public virtual SOCIETY SOCIETY { get; set; }
        public virtual student student { get; set; }
    }
}
