//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST_APIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIETY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOCIETY()
        {
            this.EVENT = new HashSet<EVENT>();
            this.POST = new HashSet<POST>();
            this.SOCIETY_REGISTRATION = new HashSet<SOCIETY_REGISTRATION>();
        }
    
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string EMAIL_LOGIN { get; set; }
        public bool INDUCTION_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENT> EVENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POST> POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOCIETY_REGISTRATION> SOCIETY_REGISTRATION { get; set; }
    }
}
